import copy from '../data/copy.json';
import {contentLanguage,localeBase,localeInfo,localizedSummary} from './i18n.js';
export const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function sourceURL(source){
  try{const u=new URL(typeof source==='string'?source:source?.url);return u.protocol==='https:'&&['x.com','twitter.com'].includes(u.hostname)&&/^\/thsottiaux(?:\/status\/\d+)?\/?$/.test(u.pathname)?u.href:'https://x.com/thsottiaux';}catch{return 'https://x.com/thsottiaux';}
}
export function dateLabel(date,lang){return date&&Number.isFinite(Date.parse(date))?new Intl.DateTimeFormat(localeInfo[lang]?.date||'en-GB',{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(new Date(date))+' UTC':'—';}
export function elapsedLabel(date,lang,now=Date.now()){
  const elapsed=Math.max(0,now-Date.parse(date));
  const days=Math.floor(elapsed/86400000),hours=Math.floor(elapsed%86400000/3600000);
  if(days)return lang==='zh'?`${days} 天 ${hours} 小时`:lang==='zh-Hant'?`${days} 天 ${hours} 小時`:lang==='ja'?`${days}日 ${hours}時間`:lang==='ko'?`${days}일 ${hours}시간`:`${days}d ${hours}h`;
  const minutes=Math.max(1,Math.floor(elapsed/60000));
  return lang==='zh'?`${hours} 小时 ${minutes%60} 分钟`:lang==='zh-Hant'?`${hours} 小時 ${minutes%60} 分鐘`:lang==='ja'?`${hours}時間 ${minutes%60}分`:lang==='ko'?`${hours}시간 ${minutes%60}분`:`${hours}h ${minutes%60}m`;
}
function calendarHeatmap(completed,lang,t,now){
  const dayMs=86400000,reference=new Date(now),end=new Date(Date.UTC(reference.getUTCFullYear(),reference.getUTCMonth(),reference.getUTCDate()));
  const oldest=completed.length?new Date(completed[completed.length-1].announcedAt):new Date(Date.UTC(end.getUTCFullYear(),end.getUTCMonth()-6,1));
  const start=new Date(Date.UTC(oldest.getUTCFullYear(),oldest.getUTCMonth(),1));
  const alignedStart=new Date(start);alignedStart.setUTCDate(start.getUTCDate()-((start.getUTCDay()+6)%7));
  const alignedEnd=new Date(end);alignedEnd.setUTCDate(end.getUTCDate()+((7-((end.getUTCDay()+6)%7)-1)%7));
  const weeks=Math.round((alignedEnd-alignedStart)/dayMs/7)+1;
  const key=date=>date.toISOString().slice(0,10),byDay=new Map(completed.map(event=>[key(new Date(event.announcedAt)),event]));
  const cells=[];
  for(let time=alignedStart.getTime();time<=alignedEnd.getTime();time+=dayMs){
    const date=new Date(time),inRange=date>=start&&date<=end,event=inRange?byDay.get(key(date)):null;
    if(!inRange){cells.push('<span class="heat-day outside" aria-hidden="true"></span>');continue;}
    const label=new Intl.DateTimeFormat(localeInfo[lang]?.date||'en-GB',{dateStyle:'medium',timeZone:'UTC'}).format(date);
    if(event){const tooltipId=`calendar-tip-${escape(event.id)}`,summary=localizedSummary(event,lang);cells.push(`<a class="heat-day reset-day ${event.kind==='banked'?'banked':''}" href="${escape(sourceURL(event.source))}" target="_blank" rel="noopener noreferrer" aria-label="${escape(label)}, ${t.completed}, ${t.original}" aria-describedby="${tooltipId}"><span class="calendar-tooltip" id="${tooltipId}" role="tooltip"><strong data-timestamp="${escape(event.announcedAt)}">${escape(dateLabel(event.announcedAt,lang))}</strong><b>${escape(t[event.state]||t.completed)}</b><span>${escape(summary)}</span><em>${t.original} ↗</em></span></a>`);}
    else cells.push('<span class="heat-day" aria-hidden="true"></span>');
  }
  const months=[];
  for(let month=new Date(start);month<=end;month=new Date(Date.UTC(month.getUTCFullYear(),month.getUTCMonth()+1,1))){const week=Math.floor((month-alignedStart)/dayMs/7)+1,label=new Intl.DateTimeFormat(localeInfo[lang]?.date||'en-GB',{month:'short',timeZone:'UTC'}).format(month);months.push(`<span style="grid-column:${week}/span 4">${escape(label)}</span>`);}
  const weekdays=['zh','zh-Hant'].includes(lang)?['一','','三','','五','','']:lang==='ja'?['月','','水','','金','','']:lang==='ko'?['월','','수','','금','','']:['M','','W','','F','',''];
  return `<div class="heatmap-scroll"><div class="heatmap-board" style="--heat-weeks:${weeks}"><div class="heatmap-months">${months.join('')}</div><div class="heatmap-body"><div class="heatmap-weekdays" aria-hidden="true">${weekdays.map(day=>`<span>${day}</span>`).join('')}</div><div class="heatmap-grid">${cells.join('')}</div></div></div></div>`;
}
export function renderTracker(data,lang='en',now=Date.now()){
  const t=copy[lang],events=data.events||[],posts=(data.posts||[]).slice().sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt)),live=data.collectorState==='connected',fresh=live&&data.lastSuccessAt&&now-Date.parse(data.lastSuccessAt)<900000;
  const sourceLink=event=>`<a href="${escape(sourceURL(event.source))}" target="_blank" rel="noopener noreferrer">${t.original} ↗</a>`;
  const announcementText=event=>String(event.text||'').replace(/\s+\[[^\]]+\]\(https:\/\/x\.com\/thsottiaux\/status\/\d+\)[\d.KMB]+$/i,'').trim();
  const active=events.filter(e=>e.state==='announced'&&!events.some(other=>['completed','rollout'].includes(other.state)&&other.relatedPostIds.includes(e.id))).sort((a,b)=>Date.parse(b.announcedAt)-Date.parse(a.announcedAt));
  const currentAnnouncement=active[0]||null;
  const completed=events.filter(e=>e.state==='completed').sort((a,b)=>Date.parse(b.announcedAt)-Date.parse(a.announcedAt));
  const lastCompleted=completed[0];
  const intervals=completed.slice(0,-1).map((event,index)=>Date.parse(event.announcedAt)-Date.parse(completed[index+1].announcedAt)).filter(value=>value>0);
  const formatDays=value=>{const days=value/86400000;return Number.isInteger(days)?String(days):days.toFixed(1);};
  const average=intervals.length?formatDays(intervals.reduce((sum,value)=>sum+value,0)/intervals.length):null;
  const longest=intervals.length?formatDays(Math.max(...intervals)):null;
  const metrics=`<section class="reset-metrics" aria-label="${t.metricBasis}"><article><span aria-hidden="true">↻</span><div><small>${t.resetCount}</small><strong>${completed.length}</strong></div></article><article><span aria-hidden="true">≈</span><div><small>${t.averageInterval}</small><strong>${average!==null?`${average} ${t.days}`:t.collecting}</strong></div></article><article><span aria-hidden="true">⌛</span><div><small>${t.longestWait}</small><strong>${longest!==null?`${longest} ${t.days}`:t.collecting}</strong></div></article></section>`;
  const community=`<aside class="community-card"><div class="community-art" aria-hidden="true">☁<span>✦</span></div><h2>${t.communityTitle}</h2><p>${t.communityText}</p><button class="beg-button" type="button">${t.begAction}</button><div class="beg-feedback" role="status" aria-live="polite"></div><div class="community-counts"><strong><span class="beg-total">0</span> ${t.begCount}</strong><span><span class="visitor-total">—</span> ${t.visitorCount}</span></div><div class="country-flags" aria-label="${t.begCount}"></div><small>${t.onePerIp}</small></aside>`;
  const calendar=`<div class="insight-grid"><section class="calendar-section history-calendar" id="calendar"><div class="section-heading"><div><h2>${t.calendarTitle}</h2><p>${t.calendarIntro}</p></div><div class="heatmap-legend"><span><i class="regular"></i>${t.calendarRegular}</span><span><i class="banked"></i>${t.banked}</span><span><i></i>${t.calendarNone}</span></div></div>${calendarHeatmap(completed,lang,t,now)}<p class="history-credit">${t.historyCredit} <a href="https://codex-resets.com/" target="_blank" rel="noopener noreferrer">codex-resets.com ↗</a></p></section></div>`;
  const eventById=new Map(events.map(event=>[event.id,event]));
  const postCards=posts.map((post,index)=>{const event=eventById.get(post.id),displayText=String(post.text||'').replace(/\s+When you make a selection it cannot be changed.*$/i,'').trim(),postKind=event?t.xResetPost:post.isReply?t.xReplyPost:t.xGeneralPost;return `<article class="x-post-card ${index===0?'featured':''}" data-post-index="${index}" ${event?`data-event-id="${escape(event.id)}"`:''} ${index>=3?'hidden':''}><div class="x-post-top"><div class="post-author"><img class="tibo-avatar" src="/tibo.jpg" alt="" width="48" height="48"><span class="author-copy"><strong>Tibo <i class="verified" aria-label="Verified">✓</i></strong><small>@thsottiaux · <time datetime="${escape(post.createdAt)}" data-timestamp="${escape(post.createdAt)}">${dateLabel(post.createdAt,lang)}</time></small></span></div><span class="post-more" aria-hidden="true">•••</span></div><p lang="en">${escape(displayText)}</p>${event?`<div class="post-context"><span class="type-tag ${escape(event.state)}">${t[event.state]}</span><span>${escape(localizedSummary(event,lang))}</span></div>`:''}<footer><span class="x-post-kind ${event?'reset':post.isReply?'reply':''}">${postKind}</span><span class="post-actions" aria-hidden="true">♡　↻　⌁</span><a href="${escape(sourceURL(post.url))}" target="_blank" rel="noopener noreferrer">${t.xOpenPost} ↗</a></footer></article>`;}).join('');
  const xStream=posts.length?`<section class="x-stream" id="posts"><div class="section-heading x-heading"><div><span class="live-spark"><i aria-hidden="true"></i>${fresh?t.xStreamFresh:t.manualReview}</span><h2>${t.xStreamTitle}</h2><p>${t.xStreamIntro}</p></div><strong>${posts.length} ${t.xCaptured}</strong></div><div class="x-post-grid">${postCards}</div>${posts.length>3?`<button class="post-show-more" type="button" aria-expanded="false">${t.morePosts} (${posts.length-3})</button>`:''}</section>`:'';
  const base=localeBase(lang),feedPage=`${base}rss/`;
  const channelSvg={browser:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9Z"/><path d="M10 21h4"/></svg>',email:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="3"/><path d="m4 7 8 6 8-6"/></svg>',telegram:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m21 3-7.5 18-4.2-7.3L3 9.8 21 3Z"/><path d="m9.3 13.7 5.2-4.6"/></svg>',webhook:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="6" cy="12" r="3"/><circle cx="18" cy="6" r="3"/><circle cx="18" cy="18" r="3"/><path d="m8.6 10.5 6.8-3M8.6 13.5l6.8 3"/></svg>',rss:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="5" cy="19" r="1.5"/><path d="M4 11a9 9 0 0 1 9 9M4 5a15 15 0 0 1 15 15"/></svg>'};
  const notificationCenter=`<dialog class="notify-dialog compact-notify" aria-labelledby="notify-title"><div class="notify-dialog-head"><div><h2 id="notify-title">${t.notificationCenterTitle}</h2><p>${t.notificationCenterIntro}</p></div><button class="notify-close" type="button" aria-label="${t.notificationClose}">×</button></div><div class="notify-panes">
    <article class="notify-pane browser-channel" data-notify-pane="browser"><span class="notify-icon">${channelSvg.browser}</span><div><h3>${t.channelBrowser}</h3><p>${t.channelBrowserDesc}</p></div><button class="notify-toggle channel-action" type="button">${t.browserAction}</button></article>
    <article class="notify-pane email-channel" data-notify-pane="email" hidden><span class="notify-icon">${channelSvg.email}</span><div><h3>${t.channelEmail}</h3><p>${t.channelEmailDesc}</p></div><form class="notify-form email-form"><input type="email" name="email" maxlength="254" autocomplete="email" placeholder="${t.emailPlaceholder}" required><button type="submit">${t.emailAction}</button></form></article>
    <article class="notify-pane telegram-channel" data-notify-pane="telegram" hidden><span class="notify-icon">${channelSvg.telegram}</span><div><h3>${t.channelTelegram}</h3><p>${t.channelTelegramDesc}</p></div><button class="telegram-connect channel-action" type="button">${t.telegramAction}</button><small class="telegram-unavailable" hidden>${t.telegramUnavailable}</small></article>
    <article class="notify-pane webhook-channel" data-notify-pane="webhook" hidden><span class="notify-icon">${channelSvg.webhook}</span><div><h3>${t.channelWebhook}</h3><p>${t.channelWebhookDesc}</p></div><form class="notify-form webhook-form"><input type="url" name="url" maxlength="1000" inputmode="url" autocomplete="url" placeholder="${t.webhookPlaceholder}" required><button type="submit">${t.webhookAction}</button></form></article>
    <article class="notify-pane rss-channel" data-notify-pane="rss" hidden><span class="notify-icon">${channelSvg.rss}</span><div><h3>${t.channelRss}</h3><p>${t.channelRssDesc}</p></div><a class="channel-action" href="${feedPage}">${t.rssAction}</a></article>
  </div><div class="notify-result" role="status" aria-live="polite"></div><p class="notify-privacy">${t.notifyPrivacy}</p></dialog>`;
  const channelIcons=`<div class="channel-pickers" aria-label="${t.notificationCenterTitle}"><button type="button" data-notify-channel="browser" aria-label="${t.channelBrowser}" title="${t.channelBrowser}">${channelSvg.browser}</button><button type="button" data-notify-channel="email" aria-label="${t.channelEmail}" title="${t.channelEmail}">${channelSvg.email}</button><button type="button" data-notify-channel="telegram" aria-label="${t.channelTelegram}" title="${t.channelTelegram}">${channelSvg.telegram}</button><button type="button" data-notify-channel="webhook" aria-label="${t.channelWebhook}" title="${t.channelWebhook}">${channelSvg.webhook}</button><button type="button" data-notify-channel="rss" aria-label="${t.channelRss}" title="${t.channelRss}">${channelSvg.rss}</button></div>`;
  const timeZoneToggle=`<div class="time-zone-toggle" role="group" aria-label="${t.timeDisplay}"><button type="button" data-time-mode="tibo" aria-pressed="false">${t.tiboTime}</button><button type="button" data-time-mode="local" aria-pressed="true">${t.localTime}</button></div>`;
  return `<section class="status-panel" aria-labelledby="status-title"><div class="status-top"><div><p>${t.headline}</p><h1 id="status-title">${t.statusHeadline}</h1></div><a class="source-profile" href="https://x.com/thsottiaux" target="_blank" rel="noopener noreferrer"><img class="tibo-avatar" src="/tibo.jpg" alt="" width="42" height="42"><span><strong>Tibo <i class="verified" aria-label="Verified">✓</i></strong><span>@thsottiaux ↗</span></span></a></div>
    <div class="status-grid"><div class="last-reset"><span>${t.lastConfirmed}</span><strong>${lastCompleted?elapsedLabel(lastCompleted.announcedAt,lang,now):t.noConfirmed}</strong><time datetime="${escape(lastCompleted?.announcedAt||'')}" data-timestamp="${escape(lastCompleted?.announcedAt||'')}">${lastCompleted?dateLabel(lastCompleted.announcedAt,lang):''}</time></div><div class="status-facts"><div><span>${t.nextReset}</span><strong>${active.length?t.nextAnnounced:t.noAnnouncement}</strong><small>${active.length?t.checkAnnouncement:t.noAnnouncementNote}</small></div><div><span>${t.averageInterval}</span><strong>${average!==null?`${average} ${t.days}`:t.collecting}</strong><small>${completed.length} ${t.confirmedSamples}${average!==null?` · ${t.confirmedAverage}`:''}</small></div></div></div>
    <div class="alert-box"><div><strong>${t.getNotified}</strong><span class="notify-note">${t.notifyNote}</span></div>${channelIcons}</div>
    <div class="status-foot"><span class="collection-mode ${fresh?'connected':''}"><i aria-hidden="true"></i>${fresh?t.liveMode:t.reviewMode}</span>${timeZoneToggle}<button class="refresh" type="button">↻ ${t.refresh}</button></div></section>
    ${notificationCenter}
    <p class="connection-warning" role="status" ${fresh?'hidden':''}>${live?t.stale:t.collectorBlocked}</p>
    ${metrics}
    ${currentAnnouncement?`<section class="upcoming"><div class="announcement-effects" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="announcement-orbit" aria-hidden="true"><svg viewBox="0 0 16 16"><path d="M14.949 6.547a3.94 3.94 0 0 0-.348-3.273 4.11 4.11 0 0 0-4.4-1.934A4.1 4.1 0 0 0 8.423.2 4.15 4.15 0 0 0 6.305.086a4.1 4.1 0 0 0-1.891.948 4.04 4.04 0 0 0-1.158 1.753 4.1 4.1 0 0 0-1.563.679A4 4 0 0 0 .554 4.72a3.99 3.99 0 0 0 .502 4.731 3.94 3.94 0 0 0 .346 3.274 4.11 4.11 0 0 0 4.402 1.933c.382.425.852.764 1.377.995.526.231 1.095.35 1.67.346 1.78.002 3.358-1.132 3.901-2.804a4.1 4.1 0 0 0 1.563-.68 4 4 0 0 0 1.14-1.253 3.99 3.99 0 0 0-.506-4.716m-6.097 8.406a3.05 3.05 0 0 1-1.945-.694l.096-.054 3.23-1.838a.53.53 0 0 0 .265-.455v-4.49l1.366.778q.02.011.025.035v3.722c-.003 1.653-1.361 2.992-3.037 2.996m-6.53-2.75a2.95 2.95 0 0 1-.36-2.01l.095.057L5.29 12.09a.53.53 0 0 0 .527 0l3.949-2.246v1.555a.05.05 0 0 1-.022.041L6.473 13.3c-1.454.826-3.311.335-4.15-1.098m-.85-6.94A3.02 3.02 0 0 1 3.07 3.949v3.785a.51.51 0 0 0 .262.451l3.93 2.237-1.366.779a.05.05 0 0 1-.048 0L2.585 9.342a2.98 2.98 0 0 1-1.113-4.094zm11.216 2.571L8.747 5.576l1.362-.776a.05.05 0 0 1 .048 0l3.265 1.86a3 3 0 0 1 1.173 1.207 2.96 2.96 0 0 1-.27 3.2 3.05 3.05 0 0 1-1.36.997V8.279a.52.52 0 0 0-.276-.445m1.36-2.015-.097-.057-3.226-1.855a.53.53 0 0 0-.53 0L6.249 6.153V4.598a.04.04 0 0 1 .019-.04L9.533 2.7a3.07 3.07 0 0 1 3.257.139c.474.325.843.778 1.066 1.303.223.526.289 1.103.191 1.664zM5.503 8.575 4.139 7.8a.05.05 0 0 1-.026-.037V4.049c0-.57.166-1.127.476-1.607s.752-.864 1.275-1.105a3.08 3.08 0 0 1 3.234.41l-.096.054-3.23 1.838a.53.53 0 0 0-.265.455zm.742-1.577 1.758-1 1.762 1v2l-1.755 1-1.762-1z"/></svg></div><div class="announcement-copy"><h2>${t.announced}</h2><p class="announcement-summary">${escape(localizedSummary(currentAnnouncement,lang))}</p><blockquote class="announcement-source" lang="en"><div><img src="/tibo.jpg" alt="" width="30" height="30"><span><strong>Tibo <i aria-label="Verified">✓</i></strong><small>@thsottiaux · <time datetime="${escape(currentAnnouncement.announcedAt)}" data-timestamp="${escape(currentAnnouncement.announcedAt)}">${escape(dateLabel(currentAnnouncement.announcedAt,lang))}</time></small></span></div><p>${escape(announcementText(currentAnnouncement))}</p></blockquote>${sourceLink(currentAnnouncement)}<small class="announcement-note">${t.pendingNote}</small></div></section>`:''}
    ${calendar}
    ${xStream}
    ${community}
    <details class="data-note" id="source-details"><summary>${t.sourceDetails}</summary><div class="freshness"><p>${live?t.sync:t.manualReview} <time datetime="${escape(data.lastSuccessAt||data.lastReviewAt||'')}" data-timestamp="${escape(data.lastSuccessAt||data.lastReviewAt||'')}">${dateLabel(data.lastSuccessAt||data.lastReviewAt,lang)}</time></p></div><p>${t.partial}</p><p>${t.provenance} <a href="https://x.com/thsottiaux" target="_blank" rel="noopener noreferrer">@thsottiaux ↗</a> · <a href="https://x.com/thsottiaux/with_replies" target="_blank" rel="noopener noreferrer">${t.xRepliesSource} ↗</a></p><p>${t.liveNote}</p></details>`;
}
