import copy from '../data/copy.json';
export const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function sourceURL(source){
  try{const u=new URL(typeof source==='string'?source:source?.url);return u.protocol==='https:'&&['x.com','twitter.com'].includes(u.hostname)&&/^\/thsottiaux(?:\/status\/\d+)?\/?$/.test(u.pathname)?u.href:'https://x.com/thsottiaux';}catch{return 'https://x.com/thsottiaux';}
}
export function dateLabel(date,lang){return date&&Number.isFinite(Date.parse(date))?new Intl.DateTimeFormat(lang==='zh'?'zh-CN':'en-GB',{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(new Date(date))+' UTC':'—';}
export function renderTracker(data,lang='en',now=Date.now()){
  const t=copy[lang],events=data.events||[],live=data.collectorState==='connected',fresh=live&&data.lastSuccessAt&&now-Date.parse(data.lastSuccessAt)<900000;
  const sourceLink=event=>`<a href="${escape(sourceURL(event.source))}" target="_blank" rel="noopener noreferrer">${t.original} ↗</a>`;
  const row=(event,index)=>`<article class="message-row" id="event-${event.id}" data-kind="${event.state}" data-index="${index}"><div class="message-heading"><div class="author"><span class="author-monogram" aria-hidden="true">T</span><div><strong>Tibo</strong><span>@thsottiaux</span></div></div><span class="type-tag ${event.state==='completed'?'automatic':'banked'}">${t[event.state]}</span></div><time datetime="${event.announcedAt}">${dateLabel(event.announcedAt,lang)}</time>${event.summary?.[lang]?`<p class="summary">${escape(event.summary[lang])}</p>`:''}${event.excerpt?`<span class="excerpt-label">${t.excerptLabel}</span>`:''}<p class="source-message" lang="en">${escape(event.text)}</p>${event.timingText?`<p class="timing">${t.scheduledTime}: <span lang="en">${escape(event.timingText)}</span></p>`:''}${event.relatedPostIds.length?`<div class="related-posts">${t.related}: ${event.relatedPostIds.map(id=>`<a href="https://x.com/thsottiaux/status/${id}" target="_blank" rel="noopener noreferrer">${id} ↗</a>`).join(' ')}</div>`:''}<div class="message-meta">${sourceLink(event)}<span>${event.review==='human_reviewed'?t.sourceChecked:t.ruleLabel}</span></div></article>`;
  const active=events.filter(e=>e.state==='announced'&&!events.some(other=>['completed','rollout'].includes(other.state)&&other.relatedPostIds.includes(e.id)));
  return `<div class="freshness"><p><span>${live?t.sync:t.manualReview}</span> <time datetime="${escape(data.lastSuccessAt||data.lastReviewAt||'')}">${dateLabel(data.lastSuccessAt||data.lastReviewAt,lang)}</time></p><button class="refresh" type="button">↻ ${t.refresh}</button></div><p class="connection-warning" role="status" ${fresh?'hidden':''}>${live?t.stale:t.collectorBlocked}</p>${active.length?`<section class="upcoming"><h2>${t.announced}</h2>${active.map(e=>`<p class="source-message">${escape(e.text)}</p>${sourceLink(e)}`).join('')}<p>${t.pendingNote}</p></section>`:''}<section class="message-history" id="archive"><div class="section-heading"><div><h2>${t.historyTitle}</h2><p>${t.historyIntro}</p></div><span class="record-count">${events.length}</span></div><div class="filters" role="group" aria-label="${t.filterLabel}"><button data-filter="all" aria-pressed="true">${t.all}</button>${['announced','rollout','completed','compensation','signal'].map(state=>`<button data-filter="${state}" aria-pressed="false">${t[state]}</button>`).join('')}</div><div class="message-list">${events.map(row).join('')}</div><p class="empty-state" hidden>${t.empty}</p><button class="show-more" hidden>${t.more}</button></section><div class="data-note"><p>${t.partial}</p><p>${t.provenance} <a href="https://x.com/thsottiaux" target="_blank" rel="noopener noreferrer">@thsottiaux ↗</a></p><p>${t.liveNote}</p></div>`;
}
